version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: npm i
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          command: npx netlify deploy -p -o -s ${NETLIFY_APP_ID} -a ${NETLIFY_ACCESS_TOKEN}
workflows:
  version: 2
  nightly:
    triggers:
      - schedule:
          cron: "0 1 * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
