version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest-browsers
        environment:
          TZ: Asia/Tokyo
          NODE_ENV: development
    steps:
      - checkout
      - restore_cache:
          key: dependencies-{{ checksum "package.json" }}
      - run:
          command: npm i
      - save_cache:
          key: dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - run:
          command: npm run build
      - run:
          command: npx netlify deploy --prod --site ${NETLIFY_APP_ID} --auth ${NETLIFY_ACCESS_TOKEN}
workflows:
  version: 2
  onetime:
    jobs:
      - build
  hourly:
    triggers:
      - schedule:
          cron: "0 * * * *"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
